# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6lM-Vy7yE7cAS-5aVdI7i_jbBwt_0tJ
"""

import PyPDF2

def extract_text_from_pdf(pdf_path):
    # Open the PDF file
    with open(pdf_path, 'rb') as file:
        # Create a PDF reader object
        pdf_reader = PyPDF2.PdfReader(file)

        # Initialize a variable to hold the extracted text
        text = "Introduction to Artificial Intelligence"

        # Iterate through the pages and extract text
        for page_num in range(len(pdf_reader.pages)):
            page = pdf_reader.pages[page_num]
            text += page.extract_text()

        return text

# Example usage
pdf_path = 'pdf_file.pdf'  # Replace with your PDF file path
extracted_text = extract_text_from_pdf(pdf_path)

# Print the extracted text
print(extracted_text)